apiVersion: kumquat.guidewire.com/v1beta1
kind: Template
metadata:
  name: aws-auth
  namespace: templates
spec:
  query: | #sql
    SELECT cm.data AS cm
    FROM "ConfigMap.core" AS cm
    WHERE cm.namespace = 'kube-system' AND
    json_extract(cm.data, '$.metadata.annotations.aggregate') = 'aws-auth'
  template:
    language: cue
    batchModeProcessing: true
    fileName: |
      ./output/out.yaml
    data: | #cue
      import "strings"

      _mapRoles: strings.Join([for result in DATA {result.cm.data.mapRoles}], "")

      apiVersion: "v1"
      kind: "ConfigMap"
      metadata: {
        name: "aws-auth"
        namespace: "kube-system"
      }
      data: {
        "mapRoles": _mapRoles
      }

