apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth-tenant-umbrella
  namespace: kube-system
  annotations:
      aggregate: aws-auth
data:
    mapRoles: |
        - rolearn: arn:aws:iam::111122223333:role/tenant-umbrella-role
          username: umbrella
          groups:
            - tenant:umbrella
