apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth-tenant-acme
  namespace: kube-system
  annotations:
      aggregate: aws-auth
data:
    mapRoles: |
        - rolearn: arn:aws:iam::111122223333:role/tenant-acme-role
          username: acme
          groups:
            - tenant:acme
