apiVersion: kumquat.guidewire.com/v1beta1
kind: Template
metadata:
  name: generate-role
  namespace: templates
spec:
  query: | #sql
    SELECT crd.data AS crd
    FROM "CustomResourceDefinition.apiextensions.k8s.io" AS crd
    WHERE crd.name LIKE "%.aws.upbound.io"
  template:
    language: cue
    batchModeProcessing: true
    fileName: |
      ./output/out.yaml
    data: | #cue
      unique_groups_map: {
        for result in data {
          "\(result.crd.spec.group)": result.crd.spec.group
        }
      }
      unique_groups: [ for g in unique_groups_map {g}]
      out: {
        apiVersion: "rbac.authorization.k8s.io/v1"
        kind: "ClusterRole"
        metadata:
          name: "crossplane-aws-readers-role"
        rules: [
            {
              apiGroups: unique_groups
              resources: [
                  "*"
              ]
              verbs: ["get", "list", "watch"]
            }
        ]
      }
